#!/usr/bin/env bash
# PreToolUse(Write|Edit|MultiEdit|NotebookEdit): refuse hand edits to the files
# this workspace generates. Each of these has exactly one writer, and a hand
# edit is silently reverted the next time that writer runs:
#
#   packages/providers/<pkg>/   `nx g nx-kcl:import-crd` (just provider / just seed-*-providers)
#   **/kcl.mod.lock             the kcl CLI (kcl mod add/update)
#   **/CHANGELOG.md             nx release (nx.json release.changelog.projectChangelogs)
#   docs/install-graph.md       node tools/graph/src/install-graph.ts (just graph)
#   catalog/crossplane.yaml     node tools/catalog/src/catalog.ts (just crossplane-catalog)
#   docs/crossplane-graph.md    node tools/catalog/src/catalog.ts (just crossplane-catalog)
#
# Exit 0 with no output = no decision; the normal permission flow applies.
set -uo pipefail

command -v jq >/dev/null 2>&1 || exit 0

payload=$(cat)
file=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[ -n "$file" ] || exit 0

root=${CLAUDE_PROJECT_DIR:-$PWD}
case "$file" in
    "$root"/*) rel=${file#"$root"/} ;;
    /*) exit 0 ;;                 # outside the project: not ours to police
    *) rel=$file ;;
esac

deny() {
    jq -nc --arg r "$1" '{
        hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "deny",
            permissionDecisionReason: $r
        }
    }'
    exit 0
}

case "$rel" in
    packages/providers/*/*)
        pkg=$(printf '%s' "$rel" | cut -d/ -f3)
        deny "packages/providers/$pkg is a generated schema package: \`nx g nx-kcl:import-crd\` writes it from a Crossplane provider's CRDs (see the \`just provider\` and \`just seed-*-providers\` recipes, and packages/providers/registry.yaml for the pinned sources). It carries tag:area:providers, so nx gives it no build/test/lint targets and it is excluded from \`just check\` and from releases. Regenerate it instead of editing it; if the shape is wrong, fix the generator in tools/nx-kcl or the ref in packages/providers/registry.yaml."
        ;;
    packages/providers/*)
        : # packages/providers/{crds,registry}.yaml are hand-maintained inventories
        ;;
esac

case "$rel" in
    *kcl.mod.lock)
        deny "kcl.mod.lock is written by the kcl CLI. Edit the [dependencies] table in the sibling kcl.mod (or run \`nx run <project>:add <dep>\`), then let \`kcl mod update\`/\`kcl run\` refresh the lock."
        ;;
    *CHANGELOG.md)
        deny "CHANGELOG.md is generated by \`nx release\` (nx.json: release.changelog.projectChangelogs, automaticFromRef) and pushed by .github/workflows/release.yml. Put the wording in the commit subject instead — lefthook's commit-msg job enforces Conventional Commits and that subject is what lands in the changelog."
        ;;
    docs/install-graph.md)
        deny "docs/install-graph.md is generated from devkit.toml and packages/manager/examples/values.yaml by \`just graph\` (tools/graph/src/install-graph.ts); \`just graph-check\` fails the pre-commit hook when it drifts. Change the sources and regenerate."
        ;;
    catalog/crossplane.yaml)
        deny "catalog/crossplane.yaml is the Backstage entity set, generated from packages/** (XRDs, Compositions, example XRs, provider schema packages) by \`just crossplane-catalog\` (tools/catalog/src/catalog.ts); \`just crossplane-catalog-check\` fails the pre-commit hook when it drifts. Entities are derived, so fix the source — the XRD, the Composition, the kcl.mod — or the emitter in tools/catalog, then regenerate."
        ;;
    docs/crossplane-graph.md)
        deny "docs/crossplane-graph.md (dependency graph, usage counts, refactor findings) is generated from packages/** by \`just crossplane-catalog\` (tools/catalog/src/catalog.ts); \`just crossplane-catalog-check\` fails the pre-commit hook when it drifts. Change the packages or the emitter and regenerate."
        ;;
esac

exit 0
