apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: package-registry-forgejo
  labels:
    provider: forgejo
spec:
  compositeTypeRef:
    apiVersion: cloud.example.org/v1alpha1
    kind: PackageRegistry
  mode: Pipeline
  pipeline:
    - step: render
      functionRef:
        name: function-package-registry
      input:
        apiVersion: packageregistry.fn.example.org/v1beta1
        kind: Input
        backend: forgejo
    - step: ready
      functionRef:
        name: function-auto-ready
