# Generated by `just pkgreg-models` from ghcr.io/crossplane-contrib/provider-helm:v1.3.0 (helm.m.crossplane.io/v1beta1 Release). Do not edit.

from __future__ import annotations

from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, Field
from function.models.base import Resource


class ConnectionDetail(Resource):
    apiVersion: Annotated[
        str | None, Field(description="API version of the referent.")
    ] = None
    fieldPath: Annotated[
        str | None,
        Field(
            description='If referring to a piece of an object instead of an entire object, this string\nshould contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].\nFor example, if the object reference is to a container within a pod, this would take on a value like:\n"spec.containers{name}" (where "name" refers to the name of the container that triggered\nthe event) or if no container name is specified "spec.containers[2]" (container with\nindex 2 in this pod). This syntax is chosen only to have some well-defined way of\nreferencing a part of an object.'
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description="Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description="Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
        ),
    ] = None
    namespace: Annotated[
        str | None,
        Field(
            description="Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
        ),
    ] = None
    resourceVersion: Annotated[
        str | None,
        Field(
            description="Specific resourceVersion to which this reference is made, if any.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"
        ),
    ] = None
    skipPartOfReleaseCheck: Annotated[
        bool | None,
        Field(
            description="SkipPartOfReleaseCheck skips check for meta.helm.sh/release-name annotation."
        ),
    ] = None
    toConnectionSecretKey: str | None = None
    uid: Annotated[
        str | None,
        Field(
            description="UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"
        ),
    ] = None


class PullSecretRef(Resource):
    name: Annotated[str, Field(description="Name of the secret.")]


class Chart(Resource):
    digest: Annotated[
        str | None,
        Field(
            description='Digest is the OCI image digest in the format "sha256:abc123..."\nOnly supported for OCI registries. When specified, the chart will be pulled by digest.\nCan be used alone or in combination with Version. Optional.',
            pattern="^sha256:[a-f0-9]{64}$",
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(description="Name of Helm chart, required if ChartSpec.URL not set"),
    ] = None
    pullSecretRef: Annotated[
        PullSecretRef | None,
        Field(
            description="PullSecretRef is reference to the secret containing credentials to helm repository.\nThe secret must contain 'username' and 'password' keys. Optional - if not provided,\nthe default credential chain is used (AWS IRSA, Azure/GCP Workload Identity, etc.)."
        ),
    ] = None
    repository: Annotated[
        str | None,
        Field(
            description="Repository: Helm repository URL, required if ChartSpec.URL not set"
        ),
    ] = None
    url: Annotated[
        str | None,
        Field(
            description="URL to chart package (typically .tgz), optional and overrides others fields in the spec"
        ),
    ] = None
    version: Annotated[
        str | None,
        Field(
            description="Version of Helm chart. Optional when Digest is specified.\nIf not set and Digest is not specified, gets late initialized with the latest available version.\nIf not set and Digest is specified, version is NOT late initialized to avoid spec drift.\nThe actual deployed version is always available in status.atProvider.version for observability."
        ),
    ] = None


class ConfigMapKeyRef(Resource):
    key: str | None = None
    name: str
    optional: bool | None = None


class SecretKeyRef(Resource):
    key: str | None = None
    name: str
    optional: bool | None = None


class PatchesFromItem(Resource):
    configMapKeyRef: Annotated[
        ConfigMapKeyRef | None,
        Field(
            description="DataKeySelector defines required spec to access a key of a configmap or secret"
        ),
    ] = None
    secretKeyRef: Annotated[
        SecretKeyRef | None,
        Field(
            description="DataKeySelector defines required spec to access a key of a configmap or secret"
        ),
    ] = None


class ValueFrom(Resource):
    configMapKeyRef: Annotated[
        ConfigMapKeyRef | None,
        Field(
            description="DataKeySelector defines required spec to access a key of a configmap or secret"
        ),
    ] = None
    secretKeyRef: Annotated[
        SecretKeyRef | None,
        Field(
            description="DataKeySelector defines required spec to access a key of a configmap or secret"
        ),
    ] = None


class SetItem(Resource):
    name: str
    value: str | None = None
    valueFrom: Annotated[
        ValueFrom | None,
        Field(description="ValueFromSource represents source of a value"),
    ] = None


class ValuesFromItem(Resource):
    configMapKeyRef: Annotated[
        ConfigMapKeyRef | None,
        Field(
            description="DataKeySelector defines required spec to access a key of a configmap or secret"
        ),
    ] = None
    secretKeyRef: Annotated[
        SecretKeyRef | None,
        Field(
            description="DataKeySelector defines required spec to access a key of a configmap or secret"
        ),
    ] = None


class ForProvider(Resource):
    chart: Annotated[
        Chart, Field(description="A ChartSpec defines the chart spec for a Release")
    ]
    insecureSkipTLSVerify: Annotated[
        bool | None,
        Field(
            description="InsecureSkipTLSVerify skips tls certificate checks for the chart download"
        ),
    ] = None
    maxHistory: Annotated[
        int | None,
        Field(
            description="MaxHistory limits the maximum number of revisions saved per release. Use 0 for no limit."
        ),
    ] = 20
    namespace: Annotated[
        str | None,
        Field(
            description="Namespace to install the release into.\nThe Release Managed Resource's namespace will be used if nothing is set."
        ),
    ] = None
    patchesFrom: Annotated[
        list[PatchesFromItem] | None,
        Field(
            description="PatchesFrom describe patches to be applied to the rendered manifests."
        ),
    ] = None
    plainHTTP: Annotated[
        bool | None,
        Field(
            description="PlainHTTP uses insecure HTTP connections for the chart download"
        ),
    ] = None
    set: list[SetItem] | None = None
    skipCRDs: Annotated[
        bool | None,
        Field(description="SkipCRDs skips installation of CRDs for the release."),
    ] = None
    skipCreateNamespace: Annotated[
        bool | None,
        Field(
            description="SkipCreateNamespace won't create the namespace for the release. This requires the namespace to already exist."
        ),
    ] = None
    takeOwnership: Annotated[
        bool | None,
        Field(
            description="TakeOwnership ignores Helm ownership validation and adopts pre-existing releases.\nThis is a ONE-TIME operation: after the first successful deployment, the flag is recorded\nin status.atProvider.ownershipTaken and subsequent reconciles use normal Helm validation.\nThis prevents silent adoption of unrelated resources during chart upgrades.\nUse this field to migrate manually-deployed Helm releases into Crossplane management."
        ),
    ] = None
    values: dict[str, Any] | None = None
    valuesFrom: list[ValuesFromItem] | None = None
    wait: Annotated[
        bool | None, Field(description="Wait for the release to become ready.")
    ] = None
    waitTimeout: Annotated[
        str | None,
        Field(
            description="WaitTimeout is the duration Helm will wait for the release to become\nready. Only applies if wait is also set. Defaults to 5m."
        ),
    ] = None


class ProviderConfigRef(Resource):
    kind: Annotated[str, Field(description="Kind of the referenced object.")]
    name: Annotated[str, Field(description="Name of the referenced object.")]


class WriteConnectionSecretToRef(Resource):
    name: Annotated[str, Field(description="Name of the secret.")]


class Spec(Resource):
    connectionDetails: list[ConnectionDetail] | None = None
    forProvider: Annotated[
        ForProvider,
        Field(
            description="ReleaseParameters are the configurable fields of a Release."
        ),
    ]
    managementPolicies: Annotated[
        list[Literal["Observe", "Create", "Update", "Delete", "LateInitialize", "*"]]
        | None,
        Field(
            description="THIS IS A BETA FIELD. It is on by default but can be opted out\nthrough a Crossplane feature flag.\nManagementPolicies specify the array of actions Crossplane is allowed to\ntake on the managed and external resources.\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"
        ),
    ] = ["*"]
    providerConfigRef: Annotated[
        ProviderConfigRef | None,
        Field(
            description="ProviderConfigReference specifies how the provider that will be used to\ncreate, observe, update, and delete this managed resource should be\nconfigured.",
            validate_default=True,
        ),
    ] = {"kind": "ClusterProviderConfig", "name": "default"}
    rollbackLimit: Annotated[
        int | None,
        Field(
            description="RollbackRetriesLimit is max number of attempts to retry Helm deployment by rolling back the release."
        ),
    ] = None
    writeConnectionSecretToRef: Annotated[
        WriteConnectionSecretToRef | None,
        Field(
            description="WriteConnectionSecretToReference specifies the namespace and name of a\nSecret to which any connection details for this managed resource should\nbe written. Connection details frequently include the endpoint, username,\nand password required to connect to the managed resource."
        ),
    ] = None


class AtProvider(Resource):
    digest: Annotated[
        str | None,
        Field(
            description="Digest is the last successfully deployed chart digest (for OCI charts only)."
        ),
    ] = None
    ownershipTaken: Annotated[
        bool | None,
        Field(
            description="OwnershipTaken indicates that spec.forProvider.takeOwnership was used for initial adoption.\nOnce set to true, subsequent reconciles use normal Helm validation instead of takeOwnership,\npreventing silent adoption of unrelated resources during upgrades."
        ),
    ] = None
    releaseDescription: str | None = None
    revision: int | None = None
    state: Annotated[
        str | None, Field(description="Status is the status of a release")
    ] = None
    version: Annotated[
        str | None, Field(description="Version is the actual deployed chart version.")
    ] = None


class Condition(Resource):
    lastTransitionTime: Annotated[
        AwareDatetime,
        Field(
            description="LastTransitionTime is the last time this condition transitioned from one\nstatus to another."
        ),
    ]
    message: Annotated[
        str | None,
        Field(
            description="A Message containing details about this condition's last transition from\none status to another, if any."
        ),
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
        ),
    ] = None
    reason: Annotated[
        str,
        Field(
            description="A Reason for this condition's last transition from one status to another."
        ),
    ]
    status: Annotated[
        str,
        Field(
            description="Status of this condition; is it currently True, False, or Unknown?"
        ),
    ]
    type: Annotated[
        str,
        Field(
            description="Type of this condition. At most one of each condition type may apply to\na resource at any point in time."
        ),
    ]


class Status(Resource):
    atProvider: Annotated[
        AtProvider | None,
        Field(description="ReleaseObservation are the observable fields of a Release."),
    ] = None
    conditions: Annotated[
        list[Condition] | None, Field(description="Conditions of the resource.")
    ] = None
    failed: int | None = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration is the latest metadata.generation\nwhich resulted in either a ready state, or stalled due to error\nit can not recover from without human intervention."
        ),
    ] = None
    patchesSha: str | None = None
    synced: bool | None = None


class Release(Resource):
    apiVersion: Annotated[
        str | None,
        Field(
            description="APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description="Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
        ),
    ] = None
    metadata: dict[str, Any] | None = None
    spec: Annotated[
        Spec, Field(description="A ReleaseSpec defines the desired state of a Release.")
    ]
    status: Annotated[
        Status | None,
        Field(
            description="A ReleaseStatus represents the observed state of a Release."
        ),
    ] = None
