import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// A top-level resource schema pins its kind as a literal type with a default:
//     kind: "Bucket" = "Bucket"
// Nested field schemas (spec.forProvider…, status…) carry no such line.
const KIND_RE = /^ {4}kind: "([A-Za-z0-9]+)" = "/m;

/**
 * Write `<root>/<projectRoot>/README.md` for a package generated by
 * `import-crd`: one table per `models/<apiVersion>/` of every resource kind and
 * its import path. Nested field schemas are left out (a provider dir can hold
 * hundreds), and so is `models/k8s`, the apimachinery copy `kcl import` vendors.
 *
 * `source` is the provenance stamped into main.k (without `# Source: `).
 */
export function writeProviderReadme(root: string, projectRoot: string, name: string, source: string): void {
  const pkgAbs = join(root, projectRoot);
  const modelsDir = join(pkgAbs, 'models');
  // KCL package names are imported with `-` spelled `_`.
  const pkg = name.replace(/-/g, '_');
  const versions = readdirSync(modelsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name !== 'k8s')
    .map((e) => ({
      version: e.name,
      kinds: readdirSync(join(modelsDir, e.name))
        .filter((f) => f.endsWith('.k'))
        .flatMap((f) => {
          const kind = KIND_RE.exec(readFileSync(join(modelsDir, e.name, f), 'utf8'))?.[1];
          return kind ? [{ kind, module: `${pkg}.models.${e.name}.${f.slice(0, -2)}` }] : [];
        })
        .sort((a, b) => a.kind.localeCompare(b.kind) || a.module.localeCompare(b.module)),
    }))
    .filter((v) => v.kinds.length > 0)
    // `kcl import` buckets CRDs it cannot place under a stable API version in
    // `unknown`; list the real versions first so the usage example uses one.
    .sort((a, b) => Number(a.version === 'unknown') - Number(b.version === 'unknown') || a.version.localeCompare(b.version));

  const lines = [
    `# ${name}`,
    ``,
    `KCL schemas generated from CRDs by \`kcl import -m crd\` (the`,
    `\`nx-kcl:import-crd\` generator). Generated: do not edit.`,
    // packages/providers is driven by its registry; anything else was a one-off call.
    projectRoot.startsWith('packages/providers/')
      ? `Regenerate from its row in \`packages/providers/registry.yaml\` with \`tools/providers.sh seed ${name}\`.`
      : `Regenerate with \`nx g nx-kcl:import-crd ${name} --force\` and the original source flags.`,
    ``,
    `Source: ${source}`,
    ``,
    `## Usage`,
    ``,
    `Depend on it by path from a package's \`kcl.mod\`:`,
    ``,
    '```toml',
    `[dependencies]`,
    `${name} = { path = "<relative path>/${projectRoot}" }`,
    '```',
    ``,
  ];
  const first = versions[0];
  if (first) {
    const example =
      first.version === 'unknown'
        ? [`import ${pkg}.models.unknown as m`, ``, `_t = m.${first.kinds[0].kind}`]
        : [`import ${first.kinds[0].module} as model`];
    lines.push(`Then import a model:`, ``, '```python', ...example, '```', ``);
  }
  lines.push(`## Kinds`, ``);
  for (const { version, kinds } of versions) {
    lines.push(`### ${version}`, ``);
    if (version === 'unknown') {
      // These files split one CRD into a schema per nested type that reference
      // each other unqualified, so a single file does not compile on its own:
      // import the directory as one package.
      lines.push(
        `Import the directory as one package — \`import ${pkg}.models.unknown as m\` — and use \`m.<kind>\`.`,
        ``,
        ...[...new Set(kinds.map((k) => k.kind))].map((k) => `- ${k}`),
        ``
      );
    } else {
      lines.push(`| kind | import |`, `| --- | --- |`, ...kinds.map((k) => `| ${k.kind} | \`${k.module}\` |`), ``);
    }
  }
  writeFileSync(join(pkgAbs, 'README.md'), lines.join('\n'));
}
