# Generated by `just pkgreg-models` from ghcr.io/crossplane-contrib/provider-gcp-artifact:v2.6.0 (artifact.gcp.m.upbound.io/v1beta1 RegistryRepository). Do not edit.

from __future__ import annotations

from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, Field
from function.models.base import Resource


class Condition(Resource):
    newerThan: Annotated[
        str | None, Field(description="Match versions newer than a duration.")
    ] = None
    olderThan: Annotated[
        str | None, Field(description="Match versions older than a duration.")
    ] = None
    packageNamePrefixes: Annotated[
        list[str] | None,
        Field(
            description="Match versions by package prefix. Applied on any prefix match."
        ),
    ] = None
    tagPrefixes: Annotated[
        list[str] | None,
        Field(description="Match versions by tag prefix. Applied on any prefix match."),
    ] = None
    tagState: Annotated[
        str | None,
        Field(
            description="Match versions by tag status.\nDefault value is ANY.\nPossible values are: TAGGED, UNTAGGED, ANY."
        ),
    ] = None
    versionNamePrefixes: Annotated[
        list[str] | None,
        Field(
            description="Match versions by version name prefix. Applied on any prefix match."
        ),
    ] = None


class MostRecentVersions(Resource):
    keepCount: Annotated[
        float | None, Field(description="Minimum number of versions to keep.")
    ] = None
    packageNamePrefixes: Annotated[
        list[str] | None,
        Field(
            description="Match versions by package prefix. Applied on any prefix match."
        ),
    ] = None


class CleanupPolicy(Resource):
    action: Annotated[
        str | None,
        Field(description="Policy action.\nPossible values are: DELETE, KEEP."),
    ] = None
    condition: Annotated[
        Condition | None,
        Field(
            description="Policy condition for matching versions.\nStructure is documented below."
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(description="The identifier for this object. Format specified above."),
    ] = None
    mostRecentVersions: Annotated[
        MostRecentVersions | None,
        Field(
            description="Policy condition for retaining a minimum number of versions. May only be\nspecified with a Keep action.\nStructure is documented below."
        ),
    ] = None


class DockerConfig(Resource):
    immutableTags: Annotated[
        bool | None,
        Field(
            description="The repository which enabled this flag prevents all tags from being modified, moved or deleted. This does not prevent tags from being created."
        ),
    ] = None


class MavenConfig(Resource):
    allowSnapshotOverwrites: Annotated[
        bool | None,
        Field(
            description="The repository with this flag will allow publishing the same\nsnapshot versions."
        ),
    ] = None
    versionPolicy: Annotated[
        str | None,
        Field(
            description="Version policy defines the versions that the registry will accept.\nDefault value is VERSION_POLICY_UNSPECIFIED.\nPossible values are: VERSION_POLICY_UNSPECIFIED, RELEASE, SNAPSHOT."
        ),
    ] = None


class PublicRepository(Resource):
    repositoryBase: Annotated[
        str | None,
        Field(
            description="A common public repository base for Yum.\nPossible values are: CENTOS, CENTOS_DEBUG, CENTOS_VAULT, CENTOS_STREAM, ROCKY, EPEL."
        ),
    ] = None
    repositoryPath: Annotated[
        str | None,
        Field(
            description='Specific repository from the base, e.g. "pub/rocky/9/BaseOS/x86_64/os"'
        ),
    ] = None


class AptRepository(Resource):
    publicRepository: Annotated[
        PublicRepository | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class Policy(Resource):
    resolution: Annotated[
        Literal["Required", "Optional"] | None,
        Field(
            description="Resolution specifies whether resolution of this reference is required.\nThe default is 'Required', which means the reconcile will fail if the\nreference cannot be resolved. 'Optional' means this reference will be\na no-op if it cannot be resolved."
        ),
    ] = "Required"
    resolve: Annotated[
        Literal["Always", "IfNotPresent"] | None,
        Field(
            description="Resolve specifies when this reference should be resolved. The default\nis 'IfNotPresent', which will attempt to resolve the reference only when\nthe corresponding field is not present. Use 'Always' to resolve the\nreference on every reconcile."
        ),
    ] = None


class UriRef(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class UriSelector(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class CommonRepository(Resource):
    uri: Annotated[
        str | None,
        Field(
            description='Specific uri to the registry, e.g. "https://registry-1.docker.io"'
        ),
    ] = None
    uriRef: Annotated[
        UriRef | None,
        Field(
            description="Reference to a RegistryRepository in artifact to populate uri."
        ),
    ] = None
    uriSelector: Annotated[
        UriSelector | None,
        Field(
            description="Selector for a RegistryRepository in artifact to populate uri."
        ),
    ] = None


class CustomRepository(Resource):
    uri: Annotated[
        str | None,
        Field(
            description='Specific uri to the registry, e.g. "https://registry-1.docker.io"'
        ),
    ] = None


class DockerRepository(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class MavenRepository(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class NpmRepository(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class PythonRepository(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class PasswordSecretVersionRef(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class PasswordSecretVersionSelector(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class UsernamePasswordCredentials(Resource):
    passwordSecretVersion: Annotated[
        str | None,
        Field(
            description="The Secret Manager key version that holds the password to access the\nremote repository. Must be in the format of\nprojects/{project}/secrets/{secret}/versions/{version}."
        ),
    ] = None
    passwordSecretVersionRef: Annotated[
        PasswordSecretVersionRef | None,
        Field(
            description="Reference to a SecretVersion in secretmanager to populate passwordSecretVersion."
        ),
    ] = None
    passwordSecretVersionSelector: Annotated[
        PasswordSecretVersionSelector | None,
        Field(
            description="Selector for a SecretVersion in secretmanager to populate passwordSecretVersion."
        ),
    ] = None
    username: Annotated[
        str | None, Field(description="The username to access the remote repository.")
    ] = None


class UpstreamCredentials(Resource):
    usernamePasswordCredentials: Annotated[
        UsernamePasswordCredentials | None,
        Field(
            description="Use username and password to access the remote repository.\nStructure is documented below."
        ),
    ] = None


class YumRepository(Resource):
    publicRepository: Annotated[
        PublicRepository | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class RemoteRepositoryConfig(Resource):
    aptRepository: Annotated[
        AptRepository | None,
        Field(
            description="Specific settings for an Apt remote repository.\nStructure is documented below."
        ),
    ] = None
    commonRepository: Annotated[
        CommonRepository | None,
        Field(
            description="Specific settings for an Artifact Registory remote repository.\nStructure is documented below."
        ),
    ] = None
    description: Annotated[
        str | None, Field(description="The description of the remote source.")
    ] = None
    disableUpstreamValidation: Annotated[
        bool | None,
        Field(
            description="If true, the remote repository upstream and upstream credentials will\nnot be validated."
        ),
    ] = None
    dockerRepository: Annotated[
        DockerRepository | None,
        Field(
            description="Specific settings for a Docker remote repository.\nStructure is documented below."
        ),
    ] = None
    mavenRepository: Annotated[
        MavenRepository | None,
        Field(
            description="Specific settings for a Maven remote repository.\nStructure is documented below."
        ),
    ] = None
    npmRepository: Annotated[
        NpmRepository | None,
        Field(
            description="Specific settings for an Npm remote repository.\nStructure is documented below."
        ),
    ] = None
    pythonRepository: Annotated[
        PythonRepository | None,
        Field(
            description="Specific settings for a Python remote repository.\nStructure is documented below."
        ),
    ] = None
    upstreamCredentials: Annotated[
        UpstreamCredentials | None,
        Field(
            description="The credentials used to access the remote repository.\nStructure is documented below."
        ),
    ] = None
    yumRepository: Annotated[
        YumRepository | None,
        Field(
            description="Specific settings for an Yum remote repository.\nStructure is documented below."
        ),
    ] = None


class RepositoryRef(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class RepositorySelector(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class UpstreamPolicy(Resource):
    id: Annotated[
        str | None, Field(description="The user-provided ID of the upstream policy.")
    ] = None
    priority: Annotated[
        float | None,
        Field(
            description="Entries with a greater priority value take precedence in the pull order."
        ),
    ] = None
    repository: Annotated[
        str | None,
        Field(
            description='A reference to the repository resource, for example:\n"projects/p1/locations/us-central1/repository/repo1".'
        ),
    ] = None
    repositoryRef: Annotated[
        RepositoryRef | None,
        Field(
            description="Reference to a RegistryRepository in artifact to populate repository."
        ),
    ] = None
    repositorySelector: Annotated[
        RepositorySelector | None,
        Field(
            description="Selector for a RegistryRepository in artifact to populate repository."
        ),
    ] = None


class VirtualRepositoryConfig(Resource):
    upstreamPolicies: Annotated[
        list[UpstreamPolicy] | None,
        Field(
            description="Policies that configure the upstream artifacts distributed by the Virtual\nRepository. Upstream policies cannot be set on a standard repository.\nStructure is documented below."
        ),
    ] = None


class VulnerabilityScanningConfig(Resource):
    enablementConfig: Annotated[
        str | None,
        Field(
            description="This configures whether vulnerability scanning is automatically performed for artifacts pushed to this repository.\nPossible values are: INHERITED, DISABLED."
        ),
    ] = None


class ForProvider(Resource):
    cleanupPolicies: Annotated[
        list[CleanupPolicy] | None,
        Field(
            description="Cleanup policies for this repository. Cleanup policies indicate when\ncertain package versions can be automatically deleted.\nMap keys are policy IDs supplied by users during policy creation. They must\nunique within a repository and be under 128 characters in length.\nStructure is documented below."
        ),
    ] = None
    cleanupPolicyDryRun: Annotated[
        bool | None,
        Field(
            description="If true, the cleanup pipeline is prevented from deleting versions in this\nrepository."
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(description="The user-provided description of the repository."),
    ] = None
    dockerConfig: Annotated[
        DockerConfig | None,
        Field(
            description="Docker repository config contains repository level configuration for the repositories of docker type.\nStructure is documented below."
        ),
    ] = None
    format: Annotated[
        str | None,
        Field(
            description="The format of packages that are stored in the repository. Supported formats\ncan be found here.\nYou can only create alpha formats if you are a member of the\nalpha user group."
        ),
    ] = None
    kmsKeyName: Annotated[
        str | None,
        Field(
            description="The Cloud KMS resource name of the customer managed encryption key that’s\nused to encrypt the contents of the Repository. Has the form:\nprojects/my-project/locations/my-region/keyRings/my-kr/cryptoKeys/my-key.\nThis value may not be changed after the Repository has been created."
        ),
    ] = None
    labels: Annotated[
        dict[str, str] | None,
        Field(
            description="Labels with user-defined metadata.\nThis field may contain up to 64 entries. Label keys and values may be no\nlonger than 63 characters. Label keys must begin with a lowercase letter\nand may only contain lowercase letters, numeric characters, underscores,\nand dashes."
        ),
    ] = None
    location: Annotated[
        str | None,
        Field(
            description="The name of the repository's location. In addition to specific regions,\nspecial values for multi-region locations are asia, europe, and us.\nSee here,\nor use the\ngoogle_artifact_registry_locations\ndata source for possible values."
        ),
    ] = None
    mavenConfig: Annotated[
        MavenConfig | None,
        Field(
            description="MavenRepositoryConfig is maven related repository details.\nProvides additional configuration details for repositories of the maven\nformat type.\nStructure is documented below."
        ),
    ] = None
    mode: Annotated[
        str | None,
        Field(
            description="The mode configures the repository to serve artifacts from different sources.\nDefault value is STANDARD_REPOSITORY.\nPossible values are: STANDARD_REPOSITORY, VIRTUAL_REPOSITORY, REMOTE_REPOSITORY."
        ),
    ] = None
    project: Annotated[
        str | None,
        Field(
            description="The ID of the project in which the resource belongs.\nIf it is not provided, the provider project is used."
        ),
    ] = None
    remoteRepositoryConfig: Annotated[
        RemoteRepositoryConfig | None,
        Field(
            description="Configuration specific for a Remote Repository.\nStructure is documented below."
        ),
    ] = None
    virtualRepositoryConfig: Annotated[
        VirtualRepositoryConfig | None,
        Field(
            description="Configuration specific for a Virtual Repository.\nStructure is documented below."
        ),
    ] = None
    vulnerabilityScanningConfig: Annotated[
        VulnerabilityScanningConfig | None,
        Field(
            description="Configuration for vulnerability scanning of artifacts stored in this repository.\nStructure is documented below."
        ),
    ] = None


class CleanupPolicy1(Resource):
    action: Annotated[
        str | None,
        Field(description="Policy action.\nPossible values are: DELETE, KEEP."),
    ] = None
    condition: Annotated[
        Condition | None,
        Field(
            description="Policy condition for matching versions.\nStructure is documented below."
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(description="The identifier for this object. Format specified above."),
    ] = None
    mostRecentVersions: Annotated[
        MostRecentVersions | None,
        Field(
            description="Policy condition for retaining a minimum number of versions. May only be\nspecified with a Keep action.\nStructure is documented below."
        ),
    ] = None


class AptRepository1(Resource):
    publicRepository: Annotated[
        PublicRepository | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class UriRef1(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class UriSelector1(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class CommonRepository1(Resource):
    uri: Annotated[
        str | None,
        Field(
            description='Specific uri to the registry, e.g. "https://registry-1.docker.io"'
        ),
    ] = None
    uriRef: Annotated[
        UriRef1 | None,
        Field(
            description="Reference to a RegistryRepository in artifact to populate uri."
        ),
    ] = None
    uriSelector: Annotated[
        UriSelector1 | None,
        Field(
            description="Selector for a RegistryRepository in artifact to populate uri."
        ),
    ] = None


class DockerRepository1(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class MavenRepository1(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class NpmRepository1(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class PythonRepository1(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class PasswordSecretVersionRef1(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class PasswordSecretVersionSelector1(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class UsernamePasswordCredentials1(Resource):
    passwordSecretVersion: Annotated[
        str | None,
        Field(
            description="The Secret Manager key version that holds the password to access the\nremote repository. Must be in the format of\nprojects/{project}/secrets/{secret}/versions/{version}."
        ),
    ] = None
    passwordSecretVersionRef: Annotated[
        PasswordSecretVersionRef1 | None,
        Field(
            description="Reference to a SecretVersion in secretmanager to populate passwordSecretVersion."
        ),
    ] = None
    passwordSecretVersionSelector: Annotated[
        PasswordSecretVersionSelector1 | None,
        Field(
            description="Selector for a SecretVersion in secretmanager to populate passwordSecretVersion."
        ),
    ] = None
    username: Annotated[
        str | None, Field(description="The username to access the remote repository.")
    ] = None


class UpstreamCredentials1(Resource):
    usernamePasswordCredentials: Annotated[
        UsernamePasswordCredentials1 | None,
        Field(
            description="Use username and password to access the remote repository.\nStructure is documented below."
        ),
    ] = None


class YumRepository1(Resource):
    publicRepository: Annotated[
        PublicRepository | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class RemoteRepositoryConfig1(Resource):
    aptRepository: Annotated[
        AptRepository1 | None,
        Field(
            description="Specific settings for an Apt remote repository.\nStructure is documented below."
        ),
    ] = None
    commonRepository: Annotated[
        CommonRepository1 | None,
        Field(
            description="Specific settings for an Artifact Registory remote repository.\nStructure is documented below."
        ),
    ] = None
    description: Annotated[
        str | None, Field(description="The description of the remote source.")
    ] = None
    disableUpstreamValidation: Annotated[
        bool | None,
        Field(
            description="If true, the remote repository upstream and upstream credentials will\nnot be validated."
        ),
    ] = None
    dockerRepository: Annotated[
        DockerRepository1 | None,
        Field(
            description="Specific settings for a Docker remote repository.\nStructure is documented below."
        ),
    ] = None
    mavenRepository: Annotated[
        MavenRepository1 | None,
        Field(
            description="Specific settings for a Maven remote repository.\nStructure is documented below."
        ),
    ] = None
    npmRepository: Annotated[
        NpmRepository1 | None,
        Field(
            description="Specific settings for an Npm remote repository.\nStructure is documented below."
        ),
    ] = None
    pythonRepository: Annotated[
        PythonRepository1 | None,
        Field(
            description="Specific settings for a Python remote repository.\nStructure is documented below."
        ),
    ] = None
    upstreamCredentials: Annotated[
        UpstreamCredentials1 | None,
        Field(
            description="The credentials used to access the remote repository.\nStructure is documented below."
        ),
    ] = None
    yumRepository: Annotated[
        YumRepository1 | None,
        Field(
            description="Specific settings for an Yum remote repository.\nStructure is documented below."
        ),
    ] = None


class RepositoryRef1(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class RepositorySelector1(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class UpstreamPolicy1(Resource):
    id: Annotated[
        str | None, Field(description="The user-provided ID of the upstream policy.")
    ] = None
    priority: Annotated[
        float | None,
        Field(
            description="Entries with a greater priority value take precedence in the pull order."
        ),
    ] = None
    repository: Annotated[
        str | None,
        Field(
            description='A reference to the repository resource, for example:\n"projects/p1/locations/us-central1/repository/repo1".'
        ),
    ] = None
    repositoryRef: Annotated[
        RepositoryRef1 | None,
        Field(
            description="Reference to a RegistryRepository in artifact to populate repository."
        ),
    ] = None
    repositorySelector: Annotated[
        RepositorySelector1 | None,
        Field(
            description="Selector for a RegistryRepository in artifact to populate repository."
        ),
    ] = None


class VirtualRepositoryConfig1(Resource):
    upstreamPolicies: Annotated[
        list[UpstreamPolicy1] | None,
        Field(
            description="Policies that configure the upstream artifacts distributed by the Virtual\nRepository. Upstream policies cannot be set on a standard repository.\nStructure is documented below."
        ),
    ] = None


class InitProvider(Resource):
    cleanupPolicies: Annotated[
        list[CleanupPolicy1] | None,
        Field(
            description="Cleanup policies for this repository. Cleanup policies indicate when\ncertain package versions can be automatically deleted.\nMap keys are policy IDs supplied by users during policy creation. They must\nunique within a repository and be under 128 characters in length.\nStructure is documented below."
        ),
    ] = None
    cleanupPolicyDryRun: Annotated[
        bool | None,
        Field(
            description="If true, the cleanup pipeline is prevented from deleting versions in this\nrepository."
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(description="The user-provided description of the repository."),
    ] = None
    dockerConfig: Annotated[
        DockerConfig | None,
        Field(
            description="Docker repository config contains repository level configuration for the repositories of docker type.\nStructure is documented below."
        ),
    ] = None
    format: Annotated[
        str | None,
        Field(
            description="The format of packages that are stored in the repository. Supported formats\ncan be found here.\nYou can only create alpha formats if you are a member of the\nalpha user group."
        ),
    ] = None
    kmsKeyName: Annotated[
        str | None,
        Field(
            description="The Cloud KMS resource name of the customer managed encryption key that’s\nused to encrypt the contents of the Repository. Has the form:\nprojects/my-project/locations/my-region/keyRings/my-kr/cryptoKeys/my-key.\nThis value may not be changed after the Repository has been created."
        ),
    ] = None
    labels: Annotated[
        dict[str, str] | None,
        Field(
            description="Labels with user-defined metadata.\nThis field may contain up to 64 entries. Label keys and values may be no\nlonger than 63 characters. Label keys must begin with a lowercase letter\nand may only contain lowercase letters, numeric characters, underscores,\nand dashes."
        ),
    ] = None
    mavenConfig: Annotated[
        MavenConfig | None,
        Field(
            description="MavenRepositoryConfig is maven related repository details.\nProvides additional configuration details for repositories of the maven\nformat type.\nStructure is documented below."
        ),
    ] = None
    mode: Annotated[
        str | None,
        Field(
            description="The mode configures the repository to serve artifacts from different sources.\nDefault value is STANDARD_REPOSITORY.\nPossible values are: STANDARD_REPOSITORY, VIRTUAL_REPOSITORY, REMOTE_REPOSITORY."
        ),
    ] = None
    project: Annotated[
        str | None,
        Field(
            description="The ID of the project in which the resource belongs.\nIf it is not provided, the provider project is used."
        ),
    ] = None
    remoteRepositoryConfig: Annotated[
        RemoteRepositoryConfig1 | None,
        Field(
            description="Configuration specific for a Remote Repository.\nStructure is documented below."
        ),
    ] = None
    virtualRepositoryConfig: Annotated[
        VirtualRepositoryConfig1 | None,
        Field(
            description="Configuration specific for a Virtual Repository.\nStructure is documented below."
        ),
    ] = None
    vulnerabilityScanningConfig: Annotated[
        VulnerabilityScanningConfig | None,
        Field(
            description="Configuration for vulnerability scanning of artifacts stored in this repository.\nStructure is documented below."
        ),
    ] = None


class ProviderConfigRef(Resource):
    kind: Annotated[str, Field(description="Kind of the referenced object.")]
    name: Annotated[str, Field(description="Name of the referenced object.")]


class WriteConnectionSecretToRef(Resource):
    name: Annotated[str, Field(description="Name of the secret.")]


class Spec(Resource):
    forProvider: ForProvider
    initProvider: Annotated[
        InitProvider | None,
        Field(
            description="THIS IS A BETA FIELD. It will be honored\nunless the Management Policies feature flag is disabled.\nInitProvider holds the same fields as ForProvider, with the exception\nof Identifier and other resource reference fields. The fields that are\nin InitProvider are merged into ForProvider when the resource is created.\nThe same fields are also added to the terraform ignore_changes hook, to\navoid updating them after creation. This is useful for fields that are\nrequired on creation, but we do not desire to update them after creation,\nfor example because of an external controller is managing them, like an\nautoscaler."
        ),
    ] = None
    managementPolicies: Annotated[
        list[Literal["Observe", "Create", "Update", "Delete", "LateInitialize", "*"]]
        | None,
        Field(
            description="THIS IS A BETA FIELD. It is on by default but can be opted out\nthrough a Crossplane feature flag.\nManagementPolicies specify the array of actions Crossplane is allowed to\ntake on the managed and external resources.\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"
        ),
    ] = ["*"]
    providerConfigRef: Annotated[
        ProviderConfigRef | None,
        Field(
            description="ProviderConfigReference specifies how the provider that will be used to\ncreate, observe, update, and delete this managed resource should be\nconfigured.",
            validate_default=True,
        ),
    ] = {"kind": "ClusterProviderConfig", "name": "default"}
    writeConnectionSecretToRef: Annotated[
        WriteConnectionSecretToRef | None,
        Field(
            description="WriteConnectionSecretToReference specifies the namespace and name of a\nSecret to which any connection details for this managed resource should\nbe written. Connection details frequently include the endpoint, username,\nand password required to connect to the managed resource."
        ),
    ] = None


class CleanupPolicy2(Resource):
    action: Annotated[
        str | None,
        Field(description="Policy action.\nPossible values are: DELETE, KEEP."),
    ] = None
    condition: Annotated[
        Condition | None,
        Field(
            description="Policy condition for matching versions.\nStructure is documented below."
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(description="The identifier for this object. Format specified above."),
    ] = None
    mostRecentVersions: Annotated[
        MostRecentVersions | None,
        Field(
            description="Policy condition for retaining a minimum number of versions. May only be\nspecified with a Keep action.\nStructure is documented below."
        ),
    ] = None


class AptRepository2(Resource):
    publicRepository: Annotated[
        PublicRepository | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class CommonRepository2(Resource):
    uri: Annotated[
        str | None,
        Field(
            description='Specific uri to the registry, e.g. "https://registry-1.docker.io"'
        ),
    ] = None


class DockerRepository2(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class MavenRepository2(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class NpmRepository2(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class PythonRepository2(Resource):
    customRepository: Annotated[
        CustomRepository | None,
        Field(
            description="[Deprecated, please use commonRepository instead] Settings for a remote repository with a custom uri.\nStructure is documented below."
        ),
    ] = None
    publicRepository: Annotated[
        str | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class UsernamePasswordCredentials2(Resource):
    passwordSecretVersion: Annotated[
        str | None,
        Field(
            description="The Secret Manager key version that holds the password to access the\nremote repository. Must be in the format of\nprojects/{project}/secrets/{secret}/versions/{version}."
        ),
    ] = None
    username: Annotated[
        str | None, Field(description="The username to access the remote repository.")
    ] = None


class UpstreamCredentials2(Resource):
    usernamePasswordCredentials: Annotated[
        UsernamePasswordCredentials2 | None,
        Field(
            description="Use username and password to access the remote repository.\nStructure is documented below."
        ),
    ] = None


class YumRepository2(Resource):
    publicRepository: Annotated[
        PublicRepository | None,
        Field(
            description="One of the publicly available Yum repositories supported by Artifact Registry.\nStructure is documented below."
        ),
    ] = None


class RemoteRepositoryConfig2(Resource):
    aptRepository: Annotated[
        AptRepository2 | None,
        Field(
            description="Specific settings for an Apt remote repository.\nStructure is documented below."
        ),
    ] = None
    commonRepository: Annotated[
        CommonRepository2 | None,
        Field(
            description="Specific settings for an Artifact Registory remote repository.\nStructure is documented below."
        ),
    ] = None
    description: Annotated[
        str | None, Field(description="The description of the remote source.")
    ] = None
    disableUpstreamValidation: Annotated[
        bool | None,
        Field(
            description="If true, the remote repository upstream and upstream credentials will\nnot be validated."
        ),
    ] = None
    dockerRepository: Annotated[
        DockerRepository2 | None,
        Field(
            description="Specific settings for a Docker remote repository.\nStructure is documented below."
        ),
    ] = None
    mavenRepository: Annotated[
        MavenRepository2 | None,
        Field(
            description="Specific settings for a Maven remote repository.\nStructure is documented below."
        ),
    ] = None
    npmRepository: Annotated[
        NpmRepository2 | None,
        Field(
            description="Specific settings for an Npm remote repository.\nStructure is documented below."
        ),
    ] = None
    pythonRepository: Annotated[
        PythonRepository2 | None,
        Field(
            description="Specific settings for a Python remote repository.\nStructure is documented below."
        ),
    ] = None
    upstreamCredentials: Annotated[
        UpstreamCredentials2 | None,
        Field(
            description="The credentials used to access the remote repository.\nStructure is documented below."
        ),
    ] = None
    yumRepository: Annotated[
        YumRepository2 | None,
        Field(
            description="Specific settings for an Yum remote repository.\nStructure is documented below."
        ),
    ] = None


class UpstreamPolicy2(Resource):
    id: Annotated[
        str | None, Field(description="The user-provided ID of the upstream policy.")
    ] = None
    priority: Annotated[
        float | None,
        Field(
            description="Entries with a greater priority value take precedence in the pull order."
        ),
    ] = None
    repository: Annotated[
        str | None,
        Field(
            description='A reference to the repository resource, for example:\n"projects/p1/locations/us-central1/repository/repo1".'
        ),
    ] = None


class VirtualRepositoryConfig2(Resource):
    upstreamPolicies: Annotated[
        list[UpstreamPolicy2] | None,
        Field(
            description="Policies that configure the upstream artifacts distributed by the Virtual\nRepository. Upstream policies cannot be set on a standard repository.\nStructure is documented below."
        ),
    ] = None


class VulnerabilityScanningConfig2(Resource):
    enablementConfig: Annotated[
        str | None,
        Field(
            description="This configures whether vulnerability scanning is automatically performed for artifacts pushed to this repository.\nPossible values are: INHERITED, DISABLED."
        ),
    ] = None
    enablementState: Annotated[
        str | None,
        Field(
            description="(Output)\nThis field returns whether scanning is active for this repository."
        ),
    ] = None
    enablementStateReason: Annotated[
        str | None,
        Field(
            description="(Output)\nThis provides an explanation for the state of scanning on this repository."
        ),
    ] = None


class AtProvider(Resource):
    cleanupPolicies: Annotated[
        list[CleanupPolicy2] | None,
        Field(
            description="Cleanup policies for this repository. Cleanup policies indicate when\ncertain package versions can be automatically deleted.\nMap keys are policy IDs supplied by users during policy creation. They must\nunique within a repository and be under 128 characters in length.\nStructure is documented below."
        ),
    ] = None
    cleanupPolicyDryRun: Annotated[
        bool | None,
        Field(
            description="If true, the cleanup pipeline is prevented from deleting versions in this\nrepository."
        ),
    ] = None
    createTime: Annotated[
        str | None, Field(description="The time when the repository was created.")
    ] = None
    description: Annotated[
        str | None,
        Field(description="The user-provided description of the repository."),
    ] = None
    dockerConfig: Annotated[
        DockerConfig | None,
        Field(
            description="Docker repository config contains repository level configuration for the repositories of docker type.\nStructure is documented below."
        ),
    ] = None
    effectiveLabels: Annotated[
        dict[str, str] | None,
        Field(description="for all of the labels present on the resource."),
    ] = None
    format: Annotated[
        str | None,
        Field(
            description="The format of packages that are stored in the repository. Supported formats\ncan be found here.\nYou can only create alpha formats if you are a member of the\nalpha user group."
        ),
    ] = None
    id: Annotated[
        str | None,
        Field(
            description="an identifier for the resource with format projects/{{project}}/locations/{{location}}/repositories/{{repository_id}}"
        ),
    ] = None
    kmsKeyName: Annotated[
        str | None,
        Field(
            description="The Cloud KMS resource name of the customer managed encryption key that’s\nused to encrypt the contents of the Repository. Has the form:\nprojects/my-project/locations/my-region/keyRings/my-kr/cryptoKeys/my-key.\nThis value may not be changed after the Repository has been created."
        ),
    ] = None
    labels: Annotated[
        dict[str, str] | None,
        Field(
            description="Labels with user-defined metadata.\nThis field may contain up to 64 entries. Label keys and values may be no\nlonger than 63 characters. Label keys must begin with a lowercase letter\nand may only contain lowercase letters, numeric characters, underscores,\nand dashes."
        ),
    ] = None
    location: Annotated[
        str | None,
        Field(
            description="The name of the repository's location. In addition to specific regions,\nspecial values for multi-region locations are asia, europe, and us.\nSee here,\nor use the\ngoogle_artifact_registry_locations\ndata source for possible values."
        ),
    ] = None
    mavenConfig: Annotated[
        MavenConfig | None,
        Field(
            description="MavenRepositoryConfig is maven related repository details.\nProvides additional configuration details for repositories of the maven\nformat type.\nStructure is documented below."
        ),
    ] = None
    mode: Annotated[
        str | None,
        Field(
            description="The mode configures the repository to serve artifacts from different sources.\nDefault value is STANDARD_REPOSITORY.\nPossible values are: STANDARD_REPOSITORY, VIRTUAL_REPOSITORY, REMOTE_REPOSITORY."
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(description='The name of the repository, for example:\n"repo1"'),
    ] = None
    project: Annotated[
        str | None,
        Field(
            description="The ID of the project in which the resource belongs.\nIf it is not provided, the provider project is used."
        ),
    ] = None
    remoteRepositoryConfig: Annotated[
        RemoteRepositoryConfig2 | None,
        Field(
            description="Configuration specific for a Remote Repository.\nStructure is documented below."
        ),
    ] = None
    terraformLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="The combination of labels configured directly on the resource\nand default labels configured on the provider."
        ),
    ] = None
    updateTime: Annotated[
        str | None, Field(description="The time when the repository was last updated.")
    ] = None
    virtualRepositoryConfig: Annotated[
        VirtualRepositoryConfig2 | None,
        Field(
            description="Configuration specific for a Virtual Repository.\nStructure is documented below."
        ),
    ] = None
    vulnerabilityScanningConfig: Annotated[
        VulnerabilityScanningConfig2 | None,
        Field(
            description="Configuration for vulnerability scanning of artifacts stored in this repository.\nStructure is documented below."
        ),
    ] = None


class Condition3(Resource):
    lastTransitionTime: Annotated[
        AwareDatetime,
        Field(
            description="LastTransitionTime is the last time this condition transitioned from one\nstatus to another."
        ),
    ]
    message: Annotated[
        str | None,
        Field(
            description="A Message containing details about this condition's last transition from\none status to another, if any."
        ),
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
        ),
    ] = None
    reason: Annotated[
        str,
        Field(
            description="A Reason for this condition's last transition from one status to another."
        ),
    ]
    status: Annotated[
        str,
        Field(
            description="Status of this condition; is it currently True, False, or Unknown?"
        ),
    ]
    type: Annotated[
        str,
        Field(
            description="Type of this condition. At most one of each condition type may apply to\na resource at any point in time."
        ),
    ]


class Status(Resource):
    atProvider: AtProvider | None = None
    conditions: Annotated[
        list[Condition3] | None, Field(description="Conditions of the resource.")
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration is the latest metadata.generation\nwhich resulted in either a ready state, or stalled due to error\nit can not recover from without human intervention."
        ),
    ] = None


class RegistryRepository(Resource):
    apiVersion: Annotated[
        str | None,
        Field(
            description="APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description="Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
        ),
    ] = None
    metadata: dict[str, Any] | None = None
    spec: Annotated[
        Spec,
        Field(
            description="RegistryRepositorySpec defines the desired state of RegistryRepository"
        ),
    ]
    status: Annotated[
        Status | None,
        Field(
            description="RegistryRepositoryStatus defines the observed state of RegistryRepository."
        ),
    ] = None
