# Generated by `just pkgreg-models` from ghcr.io/crossplane-contrib/provider-gcp-artifact:v2.6.0 (artifact.gcp.m.upbound.io/v1beta1 RegistryRepositoryIAMMember). Do not edit.

from __future__ import annotations

from function.models.base import Resource
from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, Field


class Condition(Resource):
    description: str | None = None
    expression: str | None = None
    title: str | None = None


class ForProvider(Resource):
    condition: Condition | None = None
    location: str | None = None
    member: str | None = None
    project: str | None = None
    repository: str | None = None
    role: str | None = None


class InitProvider(Resource):
    condition: Condition | None = None
    location: str | None = None
    member: str | None = None
    project: str | None = None
    repository: str | None = None
    role: str | None = None


class ProviderConfigRef(Resource):
    kind: Annotated[str, Field(description="Kind of the referenced object.")]
    name: Annotated[str, Field(description="Name of the referenced object.")]


class WriteConnectionSecretToRef(Resource):
    name: Annotated[str, Field(description="Name of the secret.")]


class Spec(Resource):
    forProvider: ForProvider
    initProvider: Annotated[
        InitProvider | None,
        Field(
            description="THIS IS A BETA FIELD. It will be honored\nunless the Management Policies feature flag is disabled.\nInitProvider holds the same fields as ForProvider, with the exception\nof Identifier and other resource reference fields. The fields that are\nin InitProvider are merged into ForProvider when the resource is created.\nThe same fields are also added to the terraform ignore_changes hook, to\navoid updating them after creation. This is useful for fields that are\nrequired on creation, but we do not desire to update them after creation,\nfor example because of an external controller is managing them, like an\nautoscaler."
        ),
    ] = None
    managementPolicies: Annotated[
        list[Literal["Observe", "Create", "Update", "Delete", "LateInitialize", "*"]]
        | None,
        Field(
            description="THIS IS A BETA FIELD. It is on by default but can be opted out\nthrough a Crossplane feature flag.\nManagementPolicies specify the array of actions Crossplane is allowed to\ntake on the managed and external resources.\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"
        ),
    ] = ["*"]
    providerConfigRef: Annotated[
        ProviderConfigRef | None,
        Field(
            description="ProviderConfigReference specifies how the provider that will be used to\ncreate, observe, update, and delete this managed resource should be\nconfigured.",
            validate_default=True,
        ),
    ] = {"kind": "ClusterProviderConfig", "name": "default"}
    writeConnectionSecretToRef: Annotated[
        WriteConnectionSecretToRef | None,
        Field(
            description="WriteConnectionSecretToReference specifies the namespace and name of a\nSecret to which any connection details for this managed resource should\nbe written. Connection details frequently include the endpoint, username,\nand password required to connect to the managed resource."
        ),
    ] = None


class AtProvider(Resource):
    condition: Condition | None = None
    etag: str | None = None
    id: str | None = None
    location: str | None = None
    member: str | None = None
    project: str | None = None
    repository: str | None = None
    role: str | None = None


class Condition3(Resource):
    lastTransitionTime: Annotated[
        AwareDatetime,
        Field(
            description="LastTransitionTime is the last time this condition transitioned from one\nstatus to another."
        ),
    ]
    message: Annotated[
        str | None,
        Field(
            description="A Message containing details about this condition's last transition from\none status to another, if any."
        ),
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
        ),
    ] = None
    reason: Annotated[
        str,
        Field(
            description="A Reason for this condition's last transition from one status to another."
        ),
    ]
    status: Annotated[
        str,
        Field(
            description="Status of this condition; is it currently True, False, or Unknown?"
        ),
    ]
    type: Annotated[
        str,
        Field(
            description="Type of this condition. At most one of each condition type may apply to\na resource at any point in time."
        ),
    ]


class Status(Resource):
    atProvider: AtProvider | None = None
    conditions: Annotated[
        list[Condition3] | None, Field(description="Conditions of the resource.")
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration is the latest metadata.generation\nwhich resulted in either a ready state, or stalled due to error\nit can not recover from without human intervention."
        ),
    ] = None


class RegistryRepositoryIAMMember(Resource):
    apiVersion: Annotated[
        str | None,
        Field(
            description="APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description="Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
        ),
    ] = None
    metadata: dict[str, Any] | None = None
    spec: Annotated[
        Spec,
        Field(
            description="RegistryRepositoryIAMMemberSpec defines the desired state of RegistryRepositoryIAMMember"
        ),
    ]
    status: Annotated[
        Status | None,
        Field(
            description="RegistryRepositoryIAMMemberStatus defines the observed state of RegistryRepositoryIAMMember."
        ),
    ] = None
