"""Typed models for every managed resource this function composes.

Everything below `base.py` is GENERATED by `just pkgreg-models` from the CRDs
of the pinned provider images listed in packages/providers/registry.yaml — the
Python counterpart of the KCL schema packages under packages/providers/**. Do
not edit the generated modules; regenerate them when a provider tag moves.
"""
