# Generated by `just pkgreg-models` from ghcr.io/crossplane-contrib/provider-azure-containerregistry:v2.6.0 (containerregistry.azure.m.upbound.io/v1beta1 Registry). Do not edit.

from __future__ import annotations

from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, Field
from function.models.base import Resource


class Policy(Resource):
    resolution: Annotated[
        Literal["Required", "Optional"] | None,
        Field(
            description="Resolution specifies whether resolution of this reference is required.\nThe default is 'Required', which means the reconcile will fail if the\nreference cannot be resolved. 'Optional' means this reference will be\na no-op if it cannot be resolved."
        ),
    ] = "Required"
    resolve: Annotated[
        Literal["Always", "IfNotPresent"] | None,
        Field(
            description="Resolve specifies when this reference should be resolved. The default\nis 'IfNotPresent', which will attempt to resolve the reference only when\nthe corresponding field is not present. Use 'Always' to resolve the\nreference on every reconcile."
        ),
    ] = None


class IdentityClientIdRef(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class IdentityClientIdSelector(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class Encryption(Resource):
    identityClientId: Annotated[
        str | None,
        Field(
            description="The client ID of the managed identity associated with the encryption key."
        ),
    ] = None
    identityClientIdRef: Annotated[
        IdentityClientIdRef | None,
        Field(
            description="Reference to a UserAssignedIdentity in managedidentity to populate identityClientId."
        ),
    ] = None
    identityClientIdSelector: Annotated[
        IdentityClientIdSelector | None,
        Field(
            description="Selector for a UserAssignedIdentity in managedidentity to populate identityClientId."
        ),
    ] = None
    keyVaultKeyId: Annotated[
        str | None, Field(description="The ID of the Key Vault Key.")
    ] = None


class Georeplication(Resource):
    location: Annotated[
        str | None,
        Field(
            description="A location where the container registry should be geo-replicated."
        ),
    ] = None
    regionalEndpointEnabled: Annotated[
        bool | None,
        Field(
            description="Whether regional endpoint is enabled for this Container Registry?"
        ),
    ] = None
    tags: Annotated[
        dict[str, str] | None,
        Field(description="A mapping of tags to assign to this replication location."),
    ] = None
    zoneRedundancyEnabled: Annotated[
        bool | None,
        Field(
            description="Whether zone redundancy is enabled for this Container Registry? Changing this forces a new resource to be created. Defaults to false."
        ),
    ] = None


class IdentityIdsRef(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class IdentityIdsSelector(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class Identity(Resource):
    identityIds: Annotated[
        list[str] | None,
        Field(
            description="Specifies a list of User Assigned Managed Identity IDs to be assigned to this Container Registry."
        ),
    ] = None
    identityIdsRefs: Annotated[
        list[IdentityIdsRef] | None,
        Field(
            description="References to UserAssignedIdentity in managedidentity to populate identityIds."
        ),
    ] = None
    identityIdsSelector: Annotated[
        IdentityIdsSelector | None,
        Field(
            description="Selector for a list of UserAssignedIdentity in managedidentity to populate identityIds."
        ),
    ] = None
    type: Annotated[
        str | None,
        Field(
            description="Specifies the type of Managed Service Identity that should be configured on this Container Registry. Possible values are SystemAssigned, UserAssigned, SystemAssigned, UserAssigned (to enable both)."
        ),
    ] = None


class IpRuleItem(Resource):
    action: Annotated[
        str | None,
        Field(
            description="The behaviour for requests matching this rule. At this time the only supported value is Allow"
        ),
    ] = None
    ipRange: Annotated[
        str | None,
        Field(description="The CIDR block from which requests will match the rule."),
    ] = None


class NetworkRuleSet(Resource):
    defaultAction: Annotated[
        str | None,
        Field(
            description="The behaviour for requests matching no rules. Either Allow or Deny. Defaults to Allow"
        ),
    ] = None
    ipRule: Annotated[
        list[IpRuleItem] | None,
        Field(description="One or more ip_rule blocks as defined below."),
    ] = None


class ResourceGroupNameRef(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class ResourceGroupNameSelector(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class ForProvider(Resource):
    adminEnabled: Annotated[
        bool | None,
        Field(
            description="Specifies whether the admin user is enabled. Defaults to false."
        ),
    ] = None
    anonymousPullEnabled: Annotated[
        bool | None,
        Field(
            description="Whether to allow anonymous (unauthenticated) pull access to this Container Registry. This is only supported on resources with the Standard or Premium SKU."
        ),
    ] = None
    dataEndpointEnabled: Annotated[
        bool | None,
        Field(
            description="Whether to enable dedicated data endpoints for this Container Registry? This is only supported on resources with the Premium SKU."
        ),
    ] = None
    encryption: Annotated[
        Encryption | None, Field(description="An encryption block as documented below.")
    ] = None
    exportPolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicates whether export policy is enabled. Defaults to true. In order to set it to false, make sure the public_network_access_enabled is also set to false."
        ),
    ] = None
    georeplications: Annotated[
        list[Georeplication] | None,
        Field(description="One or more georeplications blocks as documented below."),
    ] = None
    identity: Annotated[
        Identity | None, Field(description="An identity block as defined below.")
    ] = None
    location: Annotated[
        str | None,
        Field(
            description="Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created."
        ),
    ] = None
    networkRuleBypassOption: Annotated[
        str | None,
        Field(
            description="Whether to allow trusted Azure services to access a network-restricted Container Registry? Possible values are None and AzureServices. Defaults to AzureServices."
        ),
    ] = None
    networkRuleSet: Annotated[
        NetworkRuleSet | None,
        Field(description="A network_rule_set block as documented below."),
    ] = None
    publicNetworkAccessEnabled: Annotated[
        bool | None,
        Field(
            description="Whether public network access is allowed for the container registry. Defaults to true."
        ),
    ] = None
    quarantinePolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicates whether quarantine policy is enabled."
        ),
    ] = None
    resourceGroupName: Annotated[
        str | None,
        Field(
            description="The name of the resource group in which to create the Container Registry. Changing this forces a new resource to be created."
        ),
    ] = None
    resourceGroupNameRef: Annotated[
        ResourceGroupNameRef | None,
        Field(
            description="Reference to a ResourceGroup in azure to populate resourceGroupName."
        ),
    ] = None
    resourceGroupNameSelector: Annotated[
        ResourceGroupNameSelector | None,
        Field(
            description="Selector for a ResourceGroup in azure to populate resourceGroupName."
        ),
    ] = None
    retentionPolicyInDays: Annotated[
        float | None,
        Field(
            description="The number of days to retain and untagged manifest after which it gets purged."
        ),
    ] = None
    sku: Annotated[
        str | None,
        Field(
            description="The SKU name of the container registry. Possible values are Basic, Standard and Premium."
        ),
    ] = None
    tags: Annotated[
        dict[str, str] | None,
        Field(description="A mapping of tags to assign to the resource."),
    ] = None
    trustPolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicated whether trust policy is enabled. Defaults to false."
        ),
    ] = None
    zoneRedundancyEnabled: Annotated[
        bool | None,
        Field(
            description="Whether zone redundancy is enabled for this Container Registry? Changing this forces a new resource to be created. Defaults to false."
        ),
    ] = None


class IdentityClientIdRef1(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class IdentityClientIdSelector1(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class Encryption1(Resource):
    identityClientId: Annotated[
        str | None,
        Field(
            description="The client ID of the managed identity associated with the encryption key."
        ),
    ] = None
    identityClientIdRef: Annotated[
        IdentityClientIdRef1 | None,
        Field(
            description="Reference to a UserAssignedIdentity in managedidentity to populate identityClientId."
        ),
    ] = None
    identityClientIdSelector: Annotated[
        IdentityClientIdSelector1 | None,
        Field(
            description="Selector for a UserAssignedIdentity in managedidentity to populate identityClientId."
        ),
    ] = None
    keyVaultKeyId: Annotated[
        str | None, Field(description="The ID of the Key Vault Key.")
    ] = None


class IdentityIdsRef1(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class IdentityIdsSelector1(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class Identity1(Resource):
    identityIds: Annotated[
        list[str] | None,
        Field(
            description="Specifies a list of User Assigned Managed Identity IDs to be assigned to this Container Registry."
        ),
    ] = None
    identityIdsRefs: Annotated[
        list[IdentityIdsRef1] | None,
        Field(
            description="References to UserAssignedIdentity in managedidentity to populate identityIds."
        ),
    ] = None
    identityIdsSelector: Annotated[
        IdentityIdsSelector1 | None,
        Field(
            description="Selector for a list of UserAssignedIdentity in managedidentity to populate identityIds."
        ),
    ] = None
    type: Annotated[
        str | None,
        Field(
            description="Specifies the type of Managed Service Identity that should be configured on this Container Registry. Possible values are SystemAssigned, UserAssigned, SystemAssigned, UserAssigned (to enable both)."
        ),
    ] = None


class NetworkRuleSet1(Resource):
    defaultAction: Annotated[
        str | None,
        Field(
            description="The behaviour for requests matching no rules. Either Allow or Deny. Defaults to Allow"
        ),
    ] = None
    ipRule: Annotated[
        list[IpRuleItem] | None,
        Field(description="One or more ip_rule blocks as defined below."),
    ] = None


class InitProvider(Resource):
    adminEnabled: Annotated[
        bool | None,
        Field(
            description="Specifies whether the admin user is enabled. Defaults to false."
        ),
    ] = None
    anonymousPullEnabled: Annotated[
        bool | None,
        Field(
            description="Whether to allow anonymous (unauthenticated) pull access to this Container Registry. This is only supported on resources with the Standard or Premium SKU."
        ),
    ] = None
    dataEndpointEnabled: Annotated[
        bool | None,
        Field(
            description="Whether to enable dedicated data endpoints for this Container Registry? This is only supported on resources with the Premium SKU."
        ),
    ] = None
    encryption: Annotated[
        Encryption1 | None,
        Field(description="An encryption block as documented below."),
    ] = None
    exportPolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicates whether export policy is enabled. Defaults to true. In order to set it to false, make sure the public_network_access_enabled is also set to false."
        ),
    ] = None
    georeplications: Annotated[
        list[Georeplication] | None,
        Field(description="One or more georeplications blocks as documented below."),
    ] = None
    identity: Annotated[
        Identity1 | None, Field(description="An identity block as defined below.")
    ] = None
    location: Annotated[
        str | None,
        Field(
            description="Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created."
        ),
    ] = None
    networkRuleBypassOption: Annotated[
        str | None,
        Field(
            description="Whether to allow trusted Azure services to access a network-restricted Container Registry? Possible values are None and AzureServices. Defaults to AzureServices."
        ),
    ] = None
    networkRuleSet: Annotated[
        NetworkRuleSet1 | None,
        Field(description="A network_rule_set block as documented below."),
    ] = None
    publicNetworkAccessEnabled: Annotated[
        bool | None,
        Field(
            description="Whether public network access is allowed for the container registry. Defaults to true."
        ),
    ] = None
    quarantinePolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicates whether quarantine policy is enabled."
        ),
    ] = None
    retentionPolicyInDays: Annotated[
        float | None,
        Field(
            description="The number of days to retain and untagged manifest after which it gets purged."
        ),
    ] = None
    sku: Annotated[
        str | None,
        Field(
            description="The SKU name of the container registry. Possible values are Basic, Standard and Premium."
        ),
    ] = None
    tags: Annotated[
        dict[str, str] | None,
        Field(description="A mapping of tags to assign to the resource."),
    ] = None
    trustPolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicated whether trust policy is enabled. Defaults to false."
        ),
    ] = None
    zoneRedundancyEnabled: Annotated[
        bool | None,
        Field(
            description="Whether zone redundancy is enabled for this Container Registry? Changing this forces a new resource to be created. Defaults to false."
        ),
    ] = None


class ProviderConfigRef(Resource):
    kind: Annotated[str, Field(description="Kind of the referenced object.")]
    name: Annotated[str, Field(description="Name of the referenced object.")]


class WriteConnectionSecretToRef(Resource):
    name: Annotated[str, Field(description="Name of the secret.")]


class Spec(Resource):
    forProvider: ForProvider
    initProvider: Annotated[
        InitProvider | None,
        Field(
            description="THIS IS A BETA FIELD. It will be honored\nunless the Management Policies feature flag is disabled.\nInitProvider holds the same fields as ForProvider, with the exception\nof Identifier and other resource reference fields. The fields that are\nin InitProvider are merged into ForProvider when the resource is created.\nThe same fields are also added to the terraform ignore_changes hook, to\navoid updating them after creation. This is useful for fields that are\nrequired on creation, but we do not desire to update them after creation,\nfor example because of an external controller is managing them, like an\nautoscaler."
        ),
    ] = None
    managementPolicies: Annotated[
        list[Literal["Observe", "Create", "Update", "Delete", "LateInitialize", "*"]]
        | None,
        Field(
            description="THIS IS A BETA FIELD. It is on by default but can be opted out\nthrough a Crossplane feature flag.\nManagementPolicies specify the array of actions Crossplane is allowed to\ntake on the managed and external resources.\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"
        ),
    ] = ["*"]
    providerConfigRef: Annotated[
        ProviderConfigRef | None,
        Field(
            description="ProviderConfigReference specifies how the provider that will be used to\ncreate, observe, update, and delete this managed resource should be\nconfigured.",
            validate_default=True,
        ),
    ] = {"kind": "ClusterProviderConfig", "name": "default"}
    writeConnectionSecretToRef: Annotated[
        WriteConnectionSecretToRef | None,
        Field(
            description="WriteConnectionSecretToReference specifies the namespace and name of a\nSecret to which any connection details for this managed resource should\nbe written. Connection details frequently include the endpoint, username,\nand password required to connect to the managed resource."
        ),
    ] = None


class Encryption2(Resource):
    identityClientId: Annotated[
        str | None,
        Field(
            description="The client ID of the managed identity associated with the encryption key."
        ),
    ] = None
    keyVaultKeyId: Annotated[
        str | None, Field(description="The ID of the Key Vault Key.")
    ] = None


class Identity2(Resource):
    identityIds: Annotated[
        list[str] | None,
        Field(
            description="Specifies a list of User Assigned Managed Identity IDs to be assigned to this Container Registry."
        ),
    ] = None
    principalId: Annotated[
        str | None,
        Field(
            description="The Principal ID associated with this Managed Service Identity."
        ),
    ] = None
    tenantId: Annotated[
        str | None,
        Field(
            description="The Tenant ID associated with this Managed Service Identity."
        ),
    ] = None
    type: Annotated[
        str | None,
        Field(
            description="Specifies the type of Managed Service Identity that should be configured on this Container Registry. Possible values are SystemAssigned, UserAssigned, SystemAssigned, UserAssigned (to enable both)."
        ),
    ] = None


class NetworkRuleSet2(Resource):
    defaultAction: Annotated[
        str | None,
        Field(
            description="The behaviour for requests matching no rules. Either Allow or Deny. Defaults to Allow"
        ),
    ] = None
    ipRule: Annotated[
        list[IpRuleItem] | None,
        Field(description="One or more ip_rule blocks as defined below."),
    ] = None


class AtProvider(Resource):
    adminEnabled: Annotated[
        bool | None,
        Field(
            description="Specifies whether the admin user is enabled. Defaults to false."
        ),
    ] = None
    adminUsername: Annotated[
        str | None,
        Field(
            description="The Username associated with the Container Registry Admin account - if the admin account is enabled."
        ),
    ] = None
    anonymousPullEnabled: Annotated[
        bool | None,
        Field(
            description="Whether to allow anonymous (unauthenticated) pull access to this Container Registry. This is only supported on resources with the Standard or Premium SKU."
        ),
    ] = None
    dataEndpointEnabled: Annotated[
        bool | None,
        Field(
            description="Whether to enable dedicated data endpoints for this Container Registry? This is only supported on resources with the Premium SKU."
        ),
    ] = None
    dataEndpointHostNames: Annotated[
        list[str] | None,
        Field(
            description="A set of data endpoint hostnames associated with the container registry if data endpoints are enabled."
        ),
    ] = None
    encryption: Annotated[
        Encryption2 | None,
        Field(description="An encryption block as documented below."),
    ] = None
    exportPolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicates whether export policy is enabled. Defaults to true. In order to set it to false, make sure the public_network_access_enabled is also set to false."
        ),
    ] = None
    georeplications: Annotated[
        list[Georeplication] | None,
        Field(description="One or more georeplications blocks as documented below."),
    ] = None
    id: Annotated[
        str | None, Field(description="The ID of the Container Registry.")
    ] = None
    identity: Annotated[
        Identity2 | None, Field(description="An identity block as defined below.")
    ] = None
    location: Annotated[
        str | None,
        Field(
            description="Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created."
        ),
    ] = None
    loginServer: Annotated[
        str | None,
        Field(
            description="The URL that can be used to log into the container registry."
        ),
    ] = None
    networkRuleBypassOption: Annotated[
        str | None,
        Field(
            description="Whether to allow trusted Azure services to access a network-restricted Container Registry? Possible values are None and AzureServices. Defaults to AzureServices."
        ),
    ] = None
    networkRuleSet: Annotated[
        NetworkRuleSet2 | None,
        Field(description="A network_rule_set block as documented below."),
    ] = None
    publicNetworkAccessEnabled: Annotated[
        bool | None,
        Field(
            description="Whether public network access is allowed for the container registry. Defaults to true."
        ),
    ] = None
    quarantinePolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicates whether quarantine policy is enabled."
        ),
    ] = None
    resourceGroupName: Annotated[
        str | None,
        Field(
            description="The name of the resource group in which to create the Container Registry. Changing this forces a new resource to be created."
        ),
    ] = None
    retentionPolicyInDays: Annotated[
        float | None,
        Field(
            description="The number of days to retain and untagged manifest after which it gets purged."
        ),
    ] = None
    sku: Annotated[
        str | None,
        Field(
            description="The SKU name of the container registry. Possible values are Basic, Standard and Premium."
        ),
    ] = None
    tags: Annotated[
        dict[str, str] | None,
        Field(description="A mapping of tags to assign to the resource."),
    ] = None
    trustPolicyEnabled: Annotated[
        bool | None,
        Field(
            description="Boolean value that indicated whether trust policy is enabled. Defaults to false."
        ),
    ] = None
    zoneRedundancyEnabled: Annotated[
        bool | None,
        Field(
            description="Whether zone redundancy is enabled for this Container Registry? Changing this forces a new resource to be created. Defaults to false."
        ),
    ] = None


class Condition(Resource):
    lastTransitionTime: Annotated[
        AwareDatetime,
        Field(
            description="LastTransitionTime is the last time this condition transitioned from one\nstatus to another."
        ),
    ]
    message: Annotated[
        str | None,
        Field(
            description="A Message containing details about this condition's last transition from\none status to another, if any."
        ),
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
        ),
    ] = None
    reason: Annotated[
        str,
        Field(
            description="A Reason for this condition's last transition from one status to another."
        ),
    ]
    status: Annotated[
        str,
        Field(
            description="Status of this condition; is it currently True, False, or Unknown?"
        ),
    ]
    type: Annotated[
        str,
        Field(
            description="Type of this condition. At most one of each condition type may apply to\na resource at any point in time."
        ),
    ]


class Status(Resource):
    atProvider: AtProvider | None = None
    conditions: Annotated[
        list[Condition] | None, Field(description="Conditions of the resource.")
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration is the latest metadata.generation\nwhich resulted in either a ready state, or stalled due to error\nit can not recover from without human intervention."
        ),
    ] = None


class Registry(Resource):
    apiVersion: Annotated[
        str | None,
        Field(
            description="APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description="Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
        ),
    ] = None
    metadata: dict[str, Any] | None = None
    spec: Annotated[
        Spec, Field(description="RegistrySpec defines the desired state of Registry")
    ]
    status: Annotated[
        Status | None,
        Field(description="RegistryStatus defines the observed state of Registry."),
    ] = None
