# Generated by `just pkgreg-models` from ghcr.io/crossplane-contrib/provider-aws-ecr:v2.6.0 (ecr.aws.m.upbound.io/v1beta1 Repository). Do not edit.

from __future__ import annotations

from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, Field
from function.models.base import Resource


class Policy(Resource):
    resolution: Annotated[
        Literal["Required", "Optional"] | None,
        Field(
            description="Resolution specifies whether resolution of this reference is required.\nThe default is 'Required', which means the reconcile will fail if the\nreference cannot be resolved. 'Optional' means this reference will be\na no-op if it cannot be resolved."
        ),
    ] = "Required"
    resolve: Annotated[
        Literal["Always", "IfNotPresent"] | None,
        Field(
            description="Resolve specifies when this reference should be resolved. The default\nis 'IfNotPresent', which will attempt to resolve the reference only when\nthe corresponding field is not present. Use 'Always' to resolve the\nreference on every reconcile."
        ),
    ] = None


class KmsKeyRef(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class KmsKeySelector(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class EncryptionConfigurationItem(Resource):
    encryptionType: Annotated[
        str | None,
        Field(
            description="The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256."
        ),
    ] = None
    kmsKey: Annotated[
        str | None,
        Field(
            description="The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR."
        ),
    ] = None
    kmsKeyRef: Annotated[
        KmsKeyRef | None,
        Field(description="Reference to a Key in kms to populate kmsKey."),
    ] = None
    kmsKeySelector: Annotated[
        KmsKeySelector | None,
        Field(description="Selector for a Key in kms to populate kmsKey."),
    ] = None


class ImageScanningConfiguration(Resource):
    scanOnPush: Annotated[
        bool | None,
        Field(
            description="Indicates whether images are scanned after being pushed to the repository (true) or not scanned (false)."
        ),
    ] = None


class ImageTagMutabilityExclusionFilterItem(Resource):
    filter: Annotated[
        str | None,
        Field(
            description="The filter pattern to use for excluding image tags from the mutability setting. Must contain only letters, numbers, and special characters (._-). Each filter can be up to 128 characters long and can contain a maximum of 2 wildcards ()."
        ),
    ] = None
    filterType: Annotated[
        str | None, Field(description="The type of filter to use. Must be WILDCARD.")
    ] = None


class ForProvider(Resource):
    encryptionConfiguration: Annotated[
        list[EncryptionConfigurationItem] | None,
        Field(
            description="Encryption configuration for the repository. See below for schema."
        ),
    ] = None
    forceDelete: Annotated[
        bool | None,
        Field(
            description="If true, will delete the repository even if it contains images.\nDefaults to false."
        ),
    ] = None
    imageScanningConfiguration: Annotated[
        ImageScanningConfiguration | None,
        Field(
            description="Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning."
        ),
    ] = None
    imageTagMutability: Annotated[
        str | None,
        Field(
            description="The tag mutability setting for the repository. Must be one of: MUTABLE, IMMUTABLE, IMMUTABLE_WITH_EXCLUSION, or MUTABLE_WITH_EXCLUSION. Defaults to MUTABLE."
        ),
    ] = None
    imageTagMutabilityExclusionFilter: Annotated[
        list[ImageTagMutabilityExclusionFilterItem] | None,
        Field(
            description="Configuration block that defines filters to specify which image tags can override the default tag mutability setting. Only applicable when image_tag_mutability is set to IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION. See below for schema."
        ),
    ] = None
    region: Annotated[
        str,
        Field(
            description="Region where this resource will be managed. Defaults to the Region set in the provider configuration.\nRegion is the region you'd like your resource to be created in."
        ),
    ]
    tags: Annotated[
        dict[str, str] | None, Field(description="Key-value map of resource tags.")
    ] = None


class KmsKeyRef1(Resource):
    name: Annotated[str, Field(description="Name of the referenced object.")]
    namespace: Annotated[
        str | None, Field(description="Namespace of the referenced object")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for referencing.")] = (
        None
    )


class KmsKeySelector1(Resource):
    matchControllerRef: Annotated[
        bool | None,
        Field(
            description="MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
        ),
    ] = None
    matchLabels: Annotated[
        dict[str, str] | None,
        Field(
            description="MatchLabels ensures an object with matching labels is selected."
        ),
    ] = None
    namespace: Annotated[
        str | None, Field(description="Namespace for the selector")
    ] = None
    policy: Annotated[Policy | None, Field(description="Policies for selection.")] = (
        None
    )


class EncryptionConfigurationItem1(Resource):
    encryptionType: Annotated[
        str | None,
        Field(
            description="The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256."
        ),
    ] = None
    kmsKey: Annotated[
        str | None,
        Field(
            description="The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR."
        ),
    ] = None
    kmsKeyRef: Annotated[
        KmsKeyRef1 | None,
        Field(description="Reference to a Key in kms to populate kmsKey."),
    ] = None
    kmsKeySelector: Annotated[
        KmsKeySelector1 | None,
        Field(description="Selector for a Key in kms to populate kmsKey."),
    ] = None


class InitProvider(Resource):
    encryptionConfiguration: Annotated[
        list[EncryptionConfigurationItem1] | None,
        Field(
            description="Encryption configuration for the repository. See below for schema."
        ),
    ] = None
    forceDelete: Annotated[
        bool | None,
        Field(
            description="If true, will delete the repository even if it contains images.\nDefaults to false."
        ),
    ] = None
    imageScanningConfiguration: Annotated[
        ImageScanningConfiguration | None,
        Field(
            description="Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning."
        ),
    ] = None
    imageTagMutability: Annotated[
        str | None,
        Field(
            description="The tag mutability setting for the repository. Must be one of: MUTABLE, IMMUTABLE, IMMUTABLE_WITH_EXCLUSION, or MUTABLE_WITH_EXCLUSION. Defaults to MUTABLE."
        ),
    ] = None
    imageTagMutabilityExclusionFilter: Annotated[
        list[ImageTagMutabilityExclusionFilterItem] | None,
        Field(
            description="Configuration block that defines filters to specify which image tags can override the default tag mutability setting. Only applicable when image_tag_mutability is set to IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION. See below for schema."
        ),
    ] = None
    tags: Annotated[
        dict[str, str] | None, Field(description="Key-value map of resource tags.")
    ] = None


class ProviderConfigRef(Resource):
    kind: Annotated[str, Field(description="Kind of the referenced object.")]
    name: Annotated[str, Field(description="Name of the referenced object.")]


class WriteConnectionSecretToRef(Resource):
    name: Annotated[str, Field(description="Name of the secret.")]


class Spec(Resource):
    forProvider: ForProvider
    initProvider: Annotated[
        InitProvider | None,
        Field(
            description="THIS IS A BETA FIELD. It will be honored\nunless the Management Policies feature flag is disabled.\nInitProvider holds the same fields as ForProvider, with the exception\nof Identifier and other resource reference fields. The fields that are\nin InitProvider are merged into ForProvider when the resource is created.\nThe same fields are also added to the terraform ignore_changes hook, to\navoid updating them after creation. This is useful for fields that are\nrequired on creation, but we do not desire to update them after creation,\nfor example because of an external controller is managing them, like an\nautoscaler."
        ),
    ] = None
    managementPolicies: Annotated[
        list[Literal["Observe", "Create", "Update", "Delete", "LateInitialize", "*"]]
        | None,
        Field(
            description="THIS IS A BETA FIELD. It is on by default but can be opted out\nthrough a Crossplane feature flag.\nManagementPolicies specify the array of actions Crossplane is allowed to\ntake on the managed and external resources.\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"
        ),
    ] = ["*"]
    providerConfigRef: Annotated[
        ProviderConfigRef | None,
        Field(
            description="ProviderConfigReference specifies how the provider that will be used to\ncreate, observe, update, and delete this managed resource should be\nconfigured.",
            validate_default=True,
        ),
    ] = {"kind": "ClusterProviderConfig", "name": "default"}
    writeConnectionSecretToRef: Annotated[
        WriteConnectionSecretToRef | None,
        Field(
            description="WriteConnectionSecretToReference specifies the namespace and name of a\nSecret to which any connection details for this managed resource should\nbe written. Connection details frequently include the endpoint, username,\nand password required to connect to the managed resource."
        ),
    ] = None


class EncryptionConfigurationItem2(Resource):
    encryptionType: Annotated[
        str | None,
        Field(
            description="The encryption type to use for the repository. Valid values are AES256 or KMS. Defaults to AES256."
        ),
    ] = None
    kmsKey: Annotated[
        str | None,
        Field(
            description="The ARN of the KMS key to use when encryption_type is KMS. If not specified, uses the default AWS managed key for ECR."
        ),
    ] = None


class AtProvider(Resource):
    arn: Annotated[str | None, Field(description="Full ARN of the repository.")] = None
    encryptionConfiguration: Annotated[
        list[EncryptionConfigurationItem2] | None,
        Field(
            description="Encryption configuration for the repository. See below for schema."
        ),
    ] = None
    forceDelete: Annotated[
        bool | None,
        Field(
            description="If true, will delete the repository even if it contains images.\nDefaults to false."
        ),
    ] = None
    id: str | None = None
    imageScanningConfiguration: Annotated[
        ImageScanningConfiguration | None,
        Field(
            description="Configuration block that defines image scanning configuration for the repository. By default, image scanning must be manually triggered. See the ECR User Guide for more information about image scanning."
        ),
    ] = None
    imageTagMutability: Annotated[
        str | None,
        Field(
            description="The tag mutability setting for the repository. Must be one of: MUTABLE, IMMUTABLE, IMMUTABLE_WITH_EXCLUSION, or MUTABLE_WITH_EXCLUSION. Defaults to MUTABLE."
        ),
    ] = None
    imageTagMutabilityExclusionFilter: Annotated[
        list[ImageTagMutabilityExclusionFilterItem] | None,
        Field(
            description="Configuration block that defines filters to specify which image tags can override the default tag mutability setting. Only applicable when image_tag_mutability is set to IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION. See below for schema."
        ),
    ] = None
    region: Annotated[
        str | None,
        Field(
            description="Region where this resource will be managed. Defaults to the Region set in the provider configuration.\nRegion is the region you'd like your resource to be created in."
        ),
    ] = None
    registryId: Annotated[
        str | None,
        Field(description="The registry ID where the repository was created."),
    ] = None
    repositoryUrl: Annotated[
        str | None,
        Field(
            description="The URL of the repository (in the form aws_account_id.dkr.ecr.region.amazonaws.com/repositoryName)."
        ),
    ] = None
    tags: Annotated[
        dict[str, str] | None, Field(description="Key-value map of resource tags.")
    ] = None
    tagsAll: Annotated[
        dict[str, str] | None,
        Field(
            description="A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block."
        ),
    ] = None


class Condition(Resource):
    lastTransitionTime: Annotated[
        AwareDatetime,
        Field(
            description="LastTransitionTime is the last time this condition transitioned from one\nstatus to another."
        ),
    ]
    message: Annotated[
        str | None,
        Field(
            description="A Message containing details about this condition's last transition from\none status to another, if any."
        ),
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
        ),
    ] = None
    reason: Annotated[
        str,
        Field(
            description="A Reason for this condition's last transition from one status to another."
        ),
    ]
    status: Annotated[
        str,
        Field(
            description="Status of this condition; is it currently True, False, or Unknown?"
        ),
    ]
    type: Annotated[
        str,
        Field(
            description="Type of this condition. At most one of each condition type may apply to\na resource at any point in time."
        ),
    ]


class Status(Resource):
    atProvider: AtProvider | None = None
    conditions: Annotated[
        list[Condition] | None, Field(description="Conditions of the resource.")
    ] = None
    observedGeneration: Annotated[
        int | None,
        Field(
            description="ObservedGeneration is the latest metadata.generation\nwhich resulted in either a ready state, or stalled due to error\nit can not recover from without human intervention."
        ),
    ] = None


class Repository(Resource):
    apiVersion: Annotated[
        str | None,
        Field(
            description="APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description="Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
        ),
    ] = None
    metadata: dict[str, Any] | None = None
    spec: Annotated[
        Spec,
        Field(description="RepositorySpec defines the desired state of Repository"),
    ]
    status: Annotated[
        Status | None,
        Field(description="RepositoryStatus defines the observed state of Repository."),
    ] = None
